# Changes here will be overwritten by Copier; used by `copier update`.
_commit: v0.2.2-1-g3e54a67
_src_path: C:/redberry/src/python/redberry-webapp-template
app_name: MailManager
app_slug: mailmanager
github_owner: daniloreddy
