services:
  mailmanager:
    build: .
    container_name: mailmanager-dev
    restart: "no"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # environment:
    #   - MAILMANAGER_API_KEY=changeme
    #   - MAILMANAGER_PORT=8080
