services:
  mailmanager:
    build: .
    container_name: mailmanager-dev
    restart: "no"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
