services:
  mailmanager:
    image: ghcr.io/daniloreddy/mailmanager:main
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - SPAMASSASSIN_HOST=spamassassin
      # - MAILMANAGER_API_KEY=changeme
      # - MAILMANAGER_PORT=8080
    restart: unless-stopped
    depends_on:
      - spamassassin

  spamassassin:
    image: instantlinux/spamassassin:latest
    restart: unless-stopped