services:
  mailmanager:
    image: ghcr.io/daniloreddy/mailmanager:main
    volumes:
      - ./data:/app/data
    environment:
      - MAILMANAGER_MODE=headless
      - SPAMASSASSIN_HOST=spamassassin
    restart: unless-stopped
    depends_on:
      - spamassassin

  spamassassin:
    image: instantlinux/spamassassin:latest
    restart: unless-stopped